(()=>{
const KEY='meyertore_beta2_hoermann_work_v1';
const catalog=[
['Torblatt, Sektionen und Oberfläche',[
['garage,industrial','Torblatt / Sektionen geprüft'],['garage,industrial','Sektion ausgerichtet'],['garage,industrial','Sektion ausgetauscht'],['garage,industrial','Bodensektion ausgetauscht'],['garage,industrial','Kopfsektion ausgetauscht'],['garage,industrial','Mittelsektion ausgetauscht'],['garage,industrial','Lamelle / Paneel beschädigt'],['garage,industrial','Fingerklemmschutz geprüft'],['garage,industrial','Torblatt gereinigt'],['garage,industrial','Oberfläche ausgebessert'],['industrial','Verglasung / Füllung ausgetauscht'],['industrial','Aluminiumrahmen / Sprossen geprüft']]],
['Dichtungen und Abschlussprofile',[
['garage,industrial','Bodendichtung ausgetauscht'],['garage,industrial','Bodendichtung gekürzt / angepasst'],['garage,industrial','Seitendichtung links ausgetauscht'],['garage,industrial','Seitendichtung rechts ausgetauscht'],['garage,industrial','Sturzdichtung ausgetauscht'],['garage,industrial','Dichtung gereinigt und gepflegt'],['garage,industrial','Bodenprofil ausgetauscht'],['industrial','Schließkantenprofil ausgetauscht'],['industrial','Optosensoren im Abschlussprofil ausgetauscht']]],
['Federn und Gewichtsausgleich',[
['garage,industrial','Feder gebrochen'],['garage,industrial','Feder ausgetauscht'],['garage,industrial','Federn paarweise ausgetauscht'],['garage,industrial','Feder nachgespannt'],['garage,industrial','Federspannung eingestellt'],['garage','Zugfederpaket ausgetauscht'],['garage','Federkanal geprüft'],['industrial','Torsionsfeder ausgetauscht'],['industrial','Federwelle ausgetauscht'],['industrial','Federbruchsicherung geprüft'],['industrial','Federbruchsicherung ausgetauscht'],['garage,industrial','Gewichtsausgleich geprüft und eingestellt']]],
['Seile, Seiltrommeln und Welle',[
['garage,industrial','Seil gerissen'],['garage,industrial','Seile ausgetauscht'],['garage,industrial','Seil abgeschliffen / beschädigt'],['garage,industrial','Seilspannung eingestellt'],['garage,industrial','Seilführung korrigiert'],['garage,industrial','Seil von Trommel abgesprungen'],['garage,industrial','Seil neu aufgelegt'],['garage,industrial','Seiltrommel ausgetauscht'],['garage,industrial','Seiltrommel befestigt / eingestellt'],['industrial','Wellenkupplung geprüft'],['industrial','Wellenkupplung ausgetauscht'],['industrial','Lagerbock / Wellenlager ausgetauscht'],['industrial','Schlaffseilsicherung geprüft'],['industrial','Schlaffseilsicherung ausgetauscht']]],
['Laufschienen, Rollen, Scharniere und Beschläge',[
['garage,industrial','Laufschienen ausgerichtet'],['garage,industrial','Laufschienen befestigt'],['garage,industrial','Laufschiene ausgetauscht'],['garage,industrial','Bogenstück ausgetauscht'],['garage,industrial','Laufrolle ausgetauscht'],['garage,industrial','Laufrollen eingestellt'],['garage,industrial','Rollenhalter ausgetauscht'],['garage,industrial','Mittelscharnier ausgetauscht'],['garage,industrial','Seitenscharnier ausgetauscht'],['garage,industrial','Bodenbeschlag ausgetauscht'],['garage,industrial','Kopfrollenhalter eingestellt'],['garage,industrial','Kopfrollenhalter ausgetauscht'],['garage,industrial','Befestigungen nachgezogen'],['garage,industrial','Anker / Dübel erneuert'],['garage,industrial','Lauf und Leichtgängigkeit eingestellt']]],
['Antrieb und Mechanik',[
['garage,industrial','Antrieb geprüft'],['garage,industrial','Antrieb ausgetauscht'],['garage,industrial','Antrieb neu montiert'],['garage,industrial','Antriebsschiene ausgerichtet'],['garage,industrial','Antriebsschiene ausgetauscht'],['garage','Zahnriemen gespannt'],['garage','Zahnriemen ausgetauscht'],['garage','Führungsschlitten ausgetauscht'],['garage','Mitnehmer / Tormitnehmer ausgetauscht'],['garage','Kupplung / Entriegelung eingestellt'],['garage','SupraMatic neu eingelernt'],['garage','ProMatic neu eingelernt'],['industrial','Wellenantrieb WA geprüft'],['industrial','Wellenantrieb WA ausgetauscht'],['industrial','ITO-Antrieb geprüft / eingestellt'],['industrial','Kettenantrieb geprüft / eingestellt'],['industrial','Nothandkette eingestellt'],['industrial','Nothandkurbel geprüft'],['industrial','Getriebe auf Geräusch / Dichtigkeit geprüft']]],
['Steuerung, Programmierung und Funk',[
['garage,industrial','Bedienung / Steuerung neu angelernt'],['garage,industrial','Lernfahrten durchgeführt'],['garage,industrial','Endlagen neu eingestellt'],['garage,industrial','Kraftbegrenzung eingestellt'],['garage,industrial','Kraftbegrenzung geprüft'],['garage,industrial','Steuerung zurückgesetzt'],['garage,industrial','Fehlerspeicher ausgelesen'],['garage,industrial','Fehlercode beseitigt'],['garage','BiSecur-Handsender eingelernt'],['garage','Handsender gelöscht'],['garage','Handsenderbatterie ausgetauscht'],['garage','Funkempfänger ausgetauscht'],['garage','Codetaster eingelernt'],['garage','Innentaster ausgetauscht'],['industrial','Steuerung 360 / 445 / 460 geprüft'],['industrial','Steuerungsplatine ausgetauscht'],['industrial','Endschalter neu eingestellt'],['industrial','Drehfeld / Laufrichtung korrigiert'],['industrial','Teilöffnung eingestellt'],['industrial','Automatischer Zulauf eingestellt']]],
['Sicherheit, Sensorik und Schließkante',[
['garage,industrial','Schließkantensicherung geprüft'],['garage,industrial','Schließkantensicherung defekt'],['garage,industrial','Schließkantensicherung instandgesetzt'],['garage,industrial','Lichtschranke geprüft'],['garage,industrial','Lichtschranke ausgerichtet'],['garage,industrial','Lichtschranke ausgetauscht'],['garage,industrial','Lichtschrankenleitung repariert'],['industrial','VL – voreilende Lichtschranke defekt'],['industrial','VL – voreilende Lichtschranke ausgerichtet'],['industrial','VL – voreilende Lichtschranke ausgetauscht'],['industrial','VL-Halter / Schwenkarm eingestellt'],['industrial','Lichtgitter geprüft'],['industrial','Lichtgitter ausgerichtet'],['industrial','Lichtgitter ausgetauscht'],['industrial','Optosensor Sender ausgetauscht'],['industrial','Optosensor Empfänger ausgetauscht'],['industrial','Spiralkabel ausgetauscht'],['industrial','Schlaffseilschalter eingestellt'],['industrial','Fangvorrichtung geprüft'],['industrial','Absturzsicherung geprüft'],['garage,industrial','Reversierung / Hinderniserkennung geprüft'],['garage,industrial','Kraftmessung durchgeführt']]],
['Schlupftür, Verriegelung und Bedienung',[
['industrial','Schlupftür eingestellt'],['industrial','Schlupftürscharnier eingestellt'],['industrial','Schlupftürscharnier ausgetauscht'],['industrial','Schlupftürschließer eingestellt'],['industrial','Schlupftürkontakt geprüft'],['industrial','Schlupftürkontakt ausgetauscht'],['garage,industrial','Torgriff ausgetauscht'],['garage,industrial','Schloss ausgetauscht'],['garage,industrial','Verriegelung eingestellt'],['garage,industrial','Verriegelungsstange ausgetauscht'],['garage,industrial','Schnäpper / Riegel ausgetauscht'],['garage,industrial','Notentriegelung geprüft'],['garage,industrial','Notentriegelung eingestellt'],['garage,industrial','Notentriegelungsseil ausgetauscht']]],
['Elektrik und Leitungen',[
['garage,industrial','Netzanschluss geprüft'],['garage,industrial','Zuleitung ausgetauscht'],['garage,industrial','Stecker / Klemmstelle instandgesetzt'],['garage,industrial','Sicherung ausgetauscht'],['garage,industrial','Tasterleitung repariert'],['garage,industrial','Sensorleitung repariert'],['garage,industrial','Kabelbruch beseitigt'],['garage,industrial','Kabelbaum ausgetauscht'],['industrial','CEE-Stecker / Hauptschalter geprüft'],['industrial','Hauptschalter ausgetauscht'],['industrial','Schütz ausgetauscht'],['industrial','Motorschutz eingestellt'],['industrial','Bremsgleichrichter / Bremse geprüft']]],
['Wartung, Einstellung und Prüfung',[
['garage,industrial','Allgemeine Wartung durchgeführt'],['garage,industrial','Toranlage gereinigt'],['garage,industrial','Beschläge gereinigt'],['garage,industrial','Gelenke und Lagerstellen gewartet'],['garage,industrial','Schrauben und Befestigungen kontrolliert'],['garage,industrial','Probelauf durchgeführt'],['garage,industrial','Manuellen Lauf geprüft'],['garage,industrial','Tor ausgerichtet'],['garage,industrial','Geräusch beseitigt'],['garage,industrial','Funktionsprüfung durchgeführt'],['garage,industrial','Sicherheitsprüfung durchgeführt'],['garage,industrial','Dokumentation / Typenschild geprüft'],['garage,industrial','Mängelaufnahme durchgeführt'],['garage,industrial','Anlage außer Betrieb genommen'],['garage,industrial','Anlage wieder in Betrieb genommen']]]
];
let selected=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}})();let mode='all';
const id=(c,i)=>`hm_${c}_${i}`;const save=()=>localStorage.setItem(KEY,JSON.stringify(selected));
function inject(){const target=document.getElementById('bReport')||document.getElementById('betaTools');if(!target)return;const s=document.createElement('section');s.id='hmWork';s.className='hm-work';s.innerHTML=`<h3>Hörmann – ausgeführte Arbeiten auswählen</h3><p>Mehrere Arbeiten können gewählt und direkt in den Service-/Wartungsbericht übernommen werden.</p><div class="hm-toolbar"><input id="hmSearch" type="search" placeholder="Arbeit suchen, z. B. Feder, Seil, VL …"><button class="hm-action" id="hmClear" type="button">Auswahl löschen</button></div><div class="hm-filters"><button class="hm-filter active" data-mode="all" type="button">Alle</button><button class="hm-filter" data-mode="garage" type="button">Garagentor</button><button class="hm-filter" data-mode="industrial" type="button">Industrietor</button></div><div id="hmCatalog"></div><div class="hm-selected"><strong>Ausgewählte Arbeiten</strong><div id="hmSelected"></div><div class="hm-actions"><button class="hm-action" id="hmTransfer" type="button">In Bericht übernehmen</button><button class="hm-action" id="hmCopy" type="button">Liste kopieren</button></div></div>`;target.parentNode.insertBefore(s,target);document.getElementById('hmSearch').oninput=render;document.getElementById('hmClear').onclick=()=>{selected={};save();render()};document.querySelectorAll('.hm-filter').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('.hm-filter').forEach(x=>x.classList.toggle('active',x===b));render()});document.getElementById('hmTransfer').onclick=transfer;document.getElementById('hmCopy').onclick=copy;render()}
function render(){const q=(document.getElementById('hmSearch')?.value||'').toLowerCase();const box=document.getElementById('hmCatalog');if(!box)return;box.innerHTML=catalog.map((cat,ci)=>{const items=cat[1].map((x,ii)=>({tags:x[0],text:x[1],key:id(ci,ii)})).filter(x=>(mode==='all'||x.tags.includes(mode))&&x.text.toLowerCase().includes(q));if(!items.length)return'';return `<details class="hm-category" ${q?'open':''}><summary>${cat[0]} <span class="hm-badge">${items.length}</span></summary><div class="hm-list">${items.map(x=>`<label class="hm-item"><input type="checkbox" data-key="${x.key}" ${selected[x.key]?'checked':''}><span>${x.text}<small>${x.tags.includes('garage')&&x.tags.includes('industrial')?'Garagen- und Industrietor':x.tags.includes('garage')?'Garagentor':'Industrietor'}</small></span><select class="hm-side" data-side="${x.key}"><option value="">ohne Seite</option><option>links</option><option>rechts</option><option>beidseitig</option></select></label>`).join('')}</div></details>`}).join('');box.querySelectorAll('[data-key]').forEach(ch=>ch.onchange=()=>{const key=ch.dataset.key;const text=ch.closest('.hm-item').querySelector('span').childNodes[0].textContent.trim();if(ch.checked)selected[key]={text,side:''};else delete selected[key];save();renderSelected()});box.querySelectorAll('[data-side]').forEach(sel=>{const k=sel.dataset.side;sel.value=selected[k]?.side||'';sel.onchange=()=>{if(selected[k]){selected[k].side=sel.value;save();renderSelected()}}});renderSelected()}
function lines(){return Object.values(selected).map(x=>`• ${x.text}${x.side?' – '+x.side:''}`)}
function renderSelected(){const b=document.getElementById('hmSelected');const l=lines();b.innerHTML=l.length?`<ol>${l.map(x=>`<li>${x.replace(/^• /,'')}</li>`).join('')}</ol>`:'<p class="hm-empty">Noch keine Arbeit ausgewählt.</p>'}
function transfer(){const l=lines();if(!l.length){alert('Bitte zuerst Arbeiten auswählen.');return}const t=document.getElementById('bWork');if(!t){alert('Berichtsfeld wurde nicht gefunden.');return}t.value=[t.value.trim(),l.join('\n')].filter(Boolean).join('\n');t.dispatchEvent(new Event('input',{bubbles:true}));if(typeof toast==='function')toast('Arbeiten in Bericht übernommen');document.getElementById('bReport')?.scrollIntoView({behavior:'smooth'})}
async function copy(){const t=lines().join('\n');if(!t)return;try{await navigator.clipboard.writeText(t);if(typeof toast==='function')toast('Liste kopiert')}catch{prompt('Liste kopieren:',t)}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',inject):inject();
})();