(function () {
  "use strict";

  const C = {
    garageSectional: "garage-sectional",
    garageSide: "garage-side-sectional",
    garageUpOver: "garage-up-over",
    garageRoll: "garage-roll",
    garageOverhead: "garage-overhead",
    garageHinged: "garage-hinged",
    collective: "collective-garage",
    industrialSectional: "industrial-sectional",
    industrialRoll: "industrial-roll",
    industrialGrille: "industrial-grille",
    highSpeed: "high-speed",
    folding: "folding",
    sliding: "sliding",
    fire: "fire",
    other: "other"
  };

  const allDoorCategories = Object.values(C);
  const garageCategories = [C.garageSectional, C.garageSide, C.garageUpOver, C.garageRoll, C.garageOverhead, C.garageHinged];
  const industrialCategories = [C.collective, C.industrialSectional, C.industrialRoll, C.industrialGrille, C.highSpeed, C.folding, C.sliding, C.fire];

  window.MEYER_CATALOG = {
    version: "2.0.0-beta.1",
    verifiedThrough: "2026-07-15",
    sources: [
      { title: "Hörmann Industrie-Sektionaltore", url: "https://www.hoermann.de/mediacenter/download/301568de/Industrie_Sektionaltore_1_.pdf" },
      { title: "Hörmann Garagen-Sektionaltore", url: "https://www.hoermann.de/fileadmin/_country/kataloge/pdf/85184_Garagen-Sectionaltore_DE.pdf" },
      { title: "Hörmann Garagentor- und Einfahrtstor-Antriebe", url: "https://www.hoermann.de/fileadmin/_country/kataloge/pdf/Garagentor-Einfahrtstor-Antriebe.pdf" },
      { title: "Hörmann Rolltore und Rollgitter", url: "https://www.hoermann.de/fileadmin/_country/kataloge/pdf/rolltore_und_rollgitter.pdf" },
      { title: "Hörmann Mediacenter", url: "https://www.hoermann.de/mediacenter/" }
    ],
    categories: [
      { id: "", label: "Bitte Torart wählen", group: "" },
      { id: C.garageSectional, label: "Garagen-Sektionaltor", group: "Garagentore" },
      { id: C.garageSide, label: "Garagen-Seitensektionaltor", group: "Garagentore" },
      { id: C.garageUpOver, label: "Berry-Schwingtor", group: "Garagentore" },
      { id: C.garageRoll, label: "Garagen-Rolltor", group: "Garagentore" },
      { id: C.garageOverhead, label: "Garagen-Deckenlauftor", group: "Garagentore" },
      { id: C.garageHinged, label: "Garagen-Drehflügeltor", group: "Garagentore" },
      { id: C.collective, label: "Sammelgaragentor", group: "Industrietore" },
      { id: C.industrialSectional, label: "Industrie-Sektionaltor", group: "Industrietore" },
      { id: C.industrialRoll, label: "Industrie-Rolltor", group: "Industrietore" },
      { id: C.industrialGrille, label: "Industrie-Rollgitter", group: "Industrietore" },
      { id: C.highSpeed, label: "Schnelllauftor", group: "Industrietore" },
      { id: C.folding, label: "Falttor", group: "Industrietore" },
      { id: C.sliding, label: "Schiebe- / Kipptor Industrie", group: "Industrietore" },
      { id: C.fire, label: "Feuerschutzvorhang / Sondertor", group: "Industrietore" },
      { id: C.other, label: "Andere / unbekannte Torart", group: "Sonstige" }
    ],
    models: [
      { id: "lpu67", name: "LPU 67 Thermo", category: C.garageSectional, era: "current", note: "Energiespartor mit thermisch getrennten 67-mm-Lamellen." },
      { id: "lpu42", name: "LPU 42", category: C.garageSectional, era: "current", note: "Doppelwandiges Garagen-Sektionaltor mit 42-mm-Lamellen." },
      { id: "lte42", name: "LTE 42", category: C.garageSectional, era: "current", note: "Einwandiges Garagen-Sektionaltor für freistehende Garagen." },
      { id: "renomatic", name: "RenoMatic", category: C.garageSectional, era: "current", note: "Aktions- und Renovierungsbaureihe auf Basis des Garagen-Sektionaltor-Programms." },
      { id: "renomatic-light", name: "RenoMatic light", category: C.garageSectional, era: "current", note: "Aktionsausführung für Renovierung und Modernisierung." },
      { id: "lpu40", name: "LPU 40", category: C.garageSectional, era: "legacy", note: "Ältere doppelwandige 40-mm-Baureihe." },
      { id: "epu40", name: "EPU 40", category: C.garageSectional, era: "legacy", note: "Ältere doppelwandige / kombinierte Garagentor-Baureihe." },
      { id: "lte40", name: "LTE 40", category: C.garageSectional, era: "legacy", note: "Ältere einwandige Garagentor-Baureihe." },
      { id: "lpu30", name: "LPU 30", category: C.garageSectional, era: "legacy", note: "Frühere Garagen-Sektionaltor-Baureihe." },
      { id: "epu30", name: "EPU 30", category: C.garageSectional, era: "legacy", note: "Frühere Garagen-Sektionaltor-Baureihe." },
      { id: "lte30", name: "LTE 30", category: C.garageSectional, era: "legacy", note: "Frühere einwandige Garagen-Sektionaltor-Baureihe." },

      { id: "hst42", name: "HST 42", category: C.garageSide, era: "current", note: "Seitlich öffnendes Garagen-Sektionaltor mit 42-mm-Lamellen." },
      { id: "hst40", name: "HST 40", category: C.garageSide, era: "legacy", note: "Ältere Baureihe des Garagen-Seitensektionaltors." },

      { id: "berry-n80", name: "Berry N 80", category: C.garageUpOver, era: "current", note: "Bewährtes Berry-Schwingtor in zahlreichen Motiven." },
      { id: "berry-df98", name: "Berry DF 98", category: C.garageUpOver, era: "current", note: "Berry-Schwingtor-Baureihe für besondere Einbausituationen." },
      { id: "berry-n500", name: "Berry N 500", category: C.garageUpOver, era: "legacy", note: "Ältere Berry-Schwingtor-Baureihe." },
      { id: "berry-n80-alt", name: "Berry N80 (ältere Ausführung)", category: C.garageUpOver, era: "legacy", note: "Frühere Beschlags- oder Motivausführung des N80." },

      { id: "rollmatic2", name: "RollMatic 2", category: C.garageRoll, era: "current", note: "Garagen-Rolltor mit aktueller RollMatic-2-Steuerung und optionaler App-Bedienung." },
      { id: "rollmatic", name: "RollMatic", category: C.garageRoll, era: "legacy", note: "Garagen-Rolltor der ersten RollMatic-Generation." },
      { id: "rollmatic-t", name: "RollMatic T", category: C.garageRoll, era: "current", note: "Garagen-Rolltor-Ausführung mit passender Steuerung." },
      { id: "rollmatic-od", name: "RollMatic OD", category: C.garageOverhead, era: "current", note: "Platzsparendes Deckenlauftor mit seitlicher Antriebsmontage." },
      { id: "dft42", name: "DFT 42", category: C.garageHinged, era: "current", note: "Zweiflügeliges Garagen-Drehflügeltor mit 42-mm-Lamellen." },

      { id: "et500", name: "ET 500", category: C.collective, era: "current", note: "Kipptor für Sammelgaragen und hohe Betätigungsfrequenz." },
      { id: "st500", name: "ST 500", category: C.collective, era: "current", note: "Schiebetor für Sammelgaragen und gewerbliche Bereiche." },
      { id: "alr-f42-s", name: "ALR F42 S", category: C.collective, era: "current", note: "Aluminium-Rahmentor für Sammelgaragen mit Lüftungsfüllungen." },

      { id: "spu-f42", name: "SPU F42", category: C.industrialSectional, era: "current", note: "Doppelwandiges Industrie-Sektionaltor der Baureihe 60 mit 42-mm-Lamellen." },
      { id: "spu-67", name: "SPU 67 Thermo", category: C.industrialSectional, era: "current", note: "Thermisch getrenntes Industrie-Sektionaltor mit 67-mm-Lamellen." },
      { id: "spu-f42-plus", name: "SPU F42 Plus", category: C.industrialSectional, era: "current", note: "Industrieausführung mit Garagentor-Ansichten und vielfältigen Beschlägen." },
      { id: "spu-f42-parcel", name: "SPU F42 Parcel", category: C.industrialSectional, era: "current", note: "Tor-Lösung für Paketdienste und getrennte Fahrzeughöhen." },
      { id: "apu-f42", name: "APU F42", category: C.industrialSectional, era: "current", note: "Aluminium-verglastes Industrie-Sektionaltor mit Stahl-Lamellensockel." },
      { id: "apu-f42-thermo", name: "APU F42 Thermo", category: C.industrialSectional, era: "current", note: "Thermisch verbesserte Rahmenkonstruktion mit 42-mm-Sockel." },
      { id: "apu-67-thermo", name: "APU 67 Thermo", category: C.industrialSectional, era: "current", note: "Thermisch getrenntes Rahmentor mit 67-mm-Stahl-Lamellensockel." },
      { id: "apu-f42-parcel", name: "APU F42 Parcel", category: C.industrialSectional, era: "current", note: "Verglaste Parcel-Ausführung für Logistik- und Paketdienste." },
      { id: "alr-f42", name: "ALR F42", category: C.industrialSectional, era: "current", note: "Vollverglastes Aluminium-Rahmentor." },
      { id: "alr-f42-thermo", name: "ALR F42 Thermo", category: C.industrialSectional, era: "current", note: "Thermisch verbesserte Aluminium-Rahmenkonstruktion." },
      { id: "alr-67-thermo", name: "ALR 67 Thermo", category: C.industrialSectional, era: "current", note: "Thermisch getrenntes Aluminium-Rahmentor mit 67-mm-Bautiefe." },
      { id: "alr-f42-glazing", name: "ALR F42 Glazing", category: C.industrialSectional, era: "current", note: "Flächenbündig verglaste Industrie-Sektionaltor-Ausführung." },
      { id: "alr-67-glazing", name: "ALR 67 Thermo Glazing", category: C.industrialSectional, era: "current", note: "Thermisch getrennte, flächenbündig verglaste Ausführung." },
      { id: "alr-f42-vitraplan", name: "ALR F42 Vitraplan", category: C.industrialSectional, era: "legacy", note: "Design-Rahmentor mit vorgehängter, flächenbündiger Verglasung." },
      { id: "spu40", name: "SPU 40", category: C.industrialSectional, era: "legacy", note: "Industrie-Sektionaltor der älteren Baureihe 40." },
      { id: "apu40", name: "APU 40", category: C.industrialSectional, era: "legacy", note: "Ältere Aluminium-Rahmentor-Baureihe mit Lamellensockel." },
      { id: "alr40", name: "ALR 40", category: C.industrialSectional, era: "legacy", note: "Ältere Aluminium-Rahmentor-Baureihe." },
      { id: "tap40", name: "TAP 40", category: C.industrialSectional, era: "legacy", note: "Frühere Industrie-Sektionaltor-Ausführung." },
      { id: "dpu", name: "DPU", category: C.industrialSectional, era: "legacy", note: "Frühere hochwärmegedämmte Industrie-Sektionaltor-Baureihe." },

      { id: "dd", name: "Rolltor DD", category: C.industrialRoll, era: "current", note: "Industrie-Rolltor-Generation für robuste Anwendungen." },
      { id: "decotherm-s", name: "Decotherm S", category: C.industrialRoll, era: "current", note: "Doppelwandiges Stahlprofil für Industrie-Rolltore." },
      { id: "decotherm-a", name: "Decotherm A", category: C.industrialRoll, era: "current", note: "Doppelwandiges Aluminiumprofil für Industrie-Rolltore." },
      { id: "hr120a", name: "HR 120 A", category: C.industrialRoll, era: "current", note: "Einwandiges Aluminium-Rolltorprofil." },
      { id: "hr120s", name: "HR 120 S", category: C.industrialRoll, era: "current", note: "Einwandiges Stahl-Rolltorprofil." },
      { id: "hr120aero", name: "HR 120 aero", category: C.industrialRoll, era: "current", note: "Lüftungsprofil für Industrie-Rolltore." },
      { id: "hr116a", name: "HR 116 A", category: C.industrialRoll, era: "legacy", note: "Ältere Aluminiumprofil-Ausführung." },
      { id: "sb-roll", name: "Rolltor SB", category: C.industrialRoll, era: "current", note: "Kompakte Rolltor-Ausführung mit Zugfedertechnik." },
      { id: "tgt", name: "TGT Tiefgaragentor", category: C.industrialRoll, era: "legacy", note: "Rolltor-Ausführung für Tief- und Sammelgaragen." },

      { id: "hg-a", name: "HG-A", category: C.industrialGrille, era: "current", note: "Aluminium-Rollgitter für Belüftung und Sichtkontakt." },
      { id: "hg-s", name: "HG-S", category: C.industrialGrille, era: "current", note: "Stahl-Rollgitter für robuste Einsatzbereiche." },
      { id: "hg-l", name: "HG-L", category: C.industrialGrille, era: "current", note: "Leichtes Aluminium-Rollgitter." },
      { id: "hg-v", name: "HG-V", category: C.industrialGrille, era: "legacy", note: "Ältere verstärkte Rollgitter-Ausführung." },
      { id: "sb-grille", name: "Rollgitter SB", category: C.industrialGrille, era: "current", note: "Kompakte Rollgitter-Ausführung mit Zugfedertechnik." },

      { id: "v4015", name: "V 4015 SEL R", category: C.highSpeed, era: "current", note: "Schnelllauftor für Innenbereiche mit SoftEdge-Abschluss." },
      { id: "v5015", name: "V 5015 SEL", category: C.highSpeed, era: "current", note: "Vertikales Schnelllauftor für Innenbereiche." },
      { id: "v5030", name: "V 5030 SEL", category: C.highSpeed, era: "current", note: "Schnelllauftor für größere Öffnungen." },
      { id: "v6020", name: "V 6020 TRL", category: C.highSpeed, era: "current", note: "Transparentes Schnelllauftor für Außenbereiche." },
      { id: "v6030", name: "V 6030 A", category: C.highSpeed, era: "current", note: "Außentor-Ausführung für Windlasten." },
      { id: "v10008", name: "V 10008", category: C.highSpeed, era: "current", note: "Großtor-Ausführung für sehr große Öffnungen." },
      { id: "hs5015n", name: "HS 5015 PU N", category: C.highSpeed, era: "current", note: "Spiral-Schnelllauftor mit PU-Paneelen und Normalbeschlag." },
      { id: "hs5015h", name: "HS 5015 PU H", category: C.highSpeed, era: "current", note: "Spiral-Schnelllauftor mit höhergeführtem Beschlag." },
      { id: "hs5015v", name: "HS 5015 PU V", category: C.highSpeed, era: "current", note: "Spiral-Schnelllauftor mit vertikalem Beschlag." },
      { id: "hs7030", name: "HS 7030 PU", category: C.highSpeed, era: "current", note: "Schnelllauftor mit wärmegedämmten Paneelen für große Öffnungen." },
      { id: "hss6530", name: "HSS 6530", category: C.highSpeed, era: "current", note: "Schnelllauf-Schiebetor für spezielle Anwendungen." },
      { id: "v2715", name: "V 2715 SEL R", category: C.highSpeed, era: "legacy", note: "Kompakte ältere Schnelllauftor-Baureihe." },

      { id: "fue", name: "FUE Falttor", category: C.folding, era: "current", note: "Aluminium-Falttor für gewerbliche und industrielle Gebäude." },
      { id: "fpu", name: "FPU Falttor", category: C.folding, era: "current", note: "Wärmegedämmtes Falttor für Industrieanwendungen." },
      { id: "fst", name: "FST Falttor", category: C.folding, era: "legacy", note: "Frühere Falttor-Ausführung." },

      { id: "st500i", name: "ST 500 Schiebetor", category: C.sliding, era: "current", note: "Schienengeführtes Schiebetor für Sammelgaragen und Industrie." },
      { id: "et500i", name: "ET 500 Kipptor", category: C.sliding, era: "current", note: "Kipptor für hohe Öffnungsfrequenzen." },
      { id: "flexfire", name: "FlexFire Feuerschutzvorhang", category: C.fire, era: "current", note: "Textiler Feuerschutzabschluss für Sonderanwendungen." },
      { id: "other-model", name: "Andere / freie Eingabe", category: "*", era: "unknown", note: "Modellbezeichnung direkt vom Typenschild übernehmen." }
    ],
    drives: [
      { id: "none", name: "Kein Antrieb / handbetätigt", categories: allDoorCategories, era: "current" },
      { id: "supramatic4e", name: "SupraMatic 4 E", categories: garageCategories, era: "current" },
      { id: "supramatic4p", name: "SupraMatic 4 P", categories: garageCategories, era: "current" },
      { id: "supramatic4ht", name: "SupraMatic HT (Serie 4)", categories: [C.industrialSectional, C.collective], era: "current" },
      { id: "promatic4", name: "ProMatic 4", categories: garageCategories, era: "current" },
      { id: "promatic4akku", name: "ProMatic 4 Akku", categories: garageCategories, era: "current" },
      { id: "supramatic3e", name: "SupraMatic E Serie 3", categories: garageCategories, era: "legacy" },
      { id: "supramatic3p", name: "SupraMatic P Serie 3", categories: garageCategories, era: "legacy" },
      { id: "supramatic3h", name: "SupraMatic H Serie 3", categories: [C.industrialSectional, C.collective], era: "legacy" },
      { id: "promatic3", name: "ProMatic Serie 3", categories: garageCategories, era: "legacy" },
      { id: "promatic3akku", name: "ProMatic Akku Serie 3", categories: garageCategories, era: "legacy" },
      { id: "supramatic2e", name: "SupraMatic E Serie 2", categories: garageCategories, era: "legacy" },
      { id: "supramatic2p", name: "SupraMatic P Serie 2", categories: garageCategories, era: "legacy" },
      { id: "supramatic2h", name: "SupraMatic H Serie 2", categories: [C.industrialSectional, C.collective], era: "legacy" },
      { id: "promatic2", name: "ProMatic Serie 2", categories: garageCategories, era: "legacy" },
      { id: "promatic2akku", name: "ProMatic Akku Serie 2", categories: garageCategories, era: "legacy" },
      { id: "supramatic1e", name: "SupraMatic E Serie 1", categories: garageCategories, era: "legacy" },
      { id: "supramatic1p", name: "SupraMatic P Serie 1", categories: garageCategories, era: "legacy" },
      { id: "promatic1", name: "ProMatic Serie 1", categories: garageCategories, era: "legacy" },
      { id: "ecomatic", name: "EcoMatic", categories: garageCategories, era: "legacy" },
      { id: "supramatic-s", name: "SupraMatic S", categories: garageCategories, era: "legacy" },
      { id: "rollmatic2-drive", name: "RollMatic 2 Antrieb", categories: [C.garageRoll], era: "current" },
      { id: "rollmatic1-drive", name: "RollMatic Antrieb Serie 1", categories: [C.garageRoll], era: "legacy" },
      { id: "wa500", name: "WA 500", categories: [C.industrialSectional, C.collective], era: "current" },
      { id: "wa500m", name: "WA 500 M", categories: [C.industrialSectional, C.collective], era: "current" },
      { id: "wa500fu", name: "WA 500 FU", categories: [C.industrialSectional, C.collective], era: "current" },
      { id: "wa500mfu", name: "WA 500 M-FU", categories: [C.industrialSectional, C.collective], era: "current" },
      { id: "ito500fu", name: "ITO 500 FU", categories: [C.industrialSectional, C.collective, C.sliding], era: "current" },
      { id: "wa400", name: "WA 400", categories: [C.industrialSectional, C.collective], era: "legacy" },
      { id: "wa400m", name: "WA 400 M", categories: [C.industrialSectional, C.collective], era: "legacy" },
      { id: "wa400fu", name: "WA 400 FU", categories: [C.industrialSectional, C.collective], era: "legacy" },
      { id: "ito400", name: "ITO 400", categories: [C.industrialSectional, C.collective, C.sliding], era: "legacy" },
      { id: "ito400fu", name: "ITO 400 FU", categories: [C.industrialSectional, C.collective, C.sliding], era: "legacy" },
      { id: "wa300s4", name: "WA 300 S4", categories: [C.industrialSectional, C.collective], era: "legacy" },
      { id: "wa300rs4", name: "WA 300 R S4", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "wa250rs4", name: "WA 250 R S4", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "sta400", name: "STA 400", categories: [C.industrialSectional, C.collective, C.sliding], era: "legacy" },
      { id: "sta500", name: "STA 500", categories: [C.collective, C.sliding], era: "current" },
      { id: "s75", name: "Direktantrieb S 75", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "s140", name: "Direktantrieb S 140", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "s200", name: "Direktantrieb S 200", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "ak", name: "Schnelllauftor-Antrieb AK / FU", categories: [C.highSpeed], era: "current" },
      { id: "bk", name: "Schnelllauftor-Antrieb BK / FU", categories: [C.highSpeed], era: "current" },
      { id: "other-drive", name: "Andere / freie Eingabe", categories: allDoorCategories, era: "unknown" }
    ],
    controls: [
      { id: "integrated", name: "Im Antrieb integriert", categories: allDoorCategories, era: "current" },
      { id: "545", name: "Steuerung 545", categories: industrialCategories, era: "current" },
      { id: "560", name: "Steuerung 560", categories: industrialCategories, era: "current" },
      { id: "360", name: "Steuerung 360", categories: industrialCategories, era: "legacy" },
      { id: "a435", name: "A 435", categories: industrialCategories, era: "legacy" },
      { id: "b435", name: "B 435", categories: industrialCategories, era: "legacy" },
      { id: "a440", name: "A 440", categories: industrialCategories, era: "legacy" },
      { id: "b440", name: "B 440", categories: industrialCategories, era: "legacy" },
      { id: "a445", name: "A 445", categories: industrialCategories, era: "legacy" },
      { id: "b445", name: "B 445", categories: industrialCategories, era: "legacy" },
      { id: "a460", name: "A 460", categories: industrialCategories, era: "legacy" },
      { id: "b460", name: "B 460", categories: industrialCategories, era: "legacy" },
      { id: "b460fu", name: "B 460 FU", categories: industrialCategories, era: "legacy" },
      { id: "445r", name: "445 R", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "460r", name: "460 R", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "b455r", name: "B 455 R", categories: [C.industrialRoll, C.industrialGrille], era: "legacy" },
      { id: "420s", name: "420 S", categories: industrialCategories, era: "legacy" },
      { id: "420t", name: "420 T", categories: industrialCategories, era: "legacy" },
      { id: "ak500", name: "AK 500 FUE-1", categories: [C.highSpeed], era: "current" },
      { id: "bk150", name: "BK 150 FUE-1", categories: [C.highSpeed], era: "current" },
      { id: "rollmatic2-control", name: "RollMatic 2 Steuerung", categories: [C.garageRoll], era: "current" },
      { id: "rollmatic1-control", name: "RollMatic Steuerung Serie 1", categories: [C.garageRoll], era: "legacy" },
      { id: "other-control", name: "Andere / freie Eingabe", categories: allDoorCategories, era: "unknown" }
    ]
  };
})();
